### ISSUE TITLE
bug: Time Limit Field is always read-only

### ISSUE THREAD

**Issue by afrozshaheenkhan** [yatt-ai/yattie#104] opened 2023-12-07 10:01 UTC
Platform: Windows

YATTIE version: 0.10.0

Current behavior: Time Limit field is always read-only and not editable

Expected behavior: Time Limit field should be editable

![image](https://github.com/yatt-ai/yattie/assets/21246549/0bcd7e91-50bc-4c51-9a8b-c8e65188d11c)

**Comment by isntlazy** [comment] 2024-01-17 11:41
@afrozshaheenkhan I checked the logic in code and as I understand, this is expected and not a bug. You can Edit this field only if your session status is "pending" which is happened when you click on Create new Session. 
@dacoaster please confirm if any changes required here

**Comment by dacoaster** [comment] 2024-01-17 14:53
@isntlazy - This field definitely should be editable on the test charter screen (pictured).  This is the only place where you can actually set the time limit.

**Comment by isntlazy** [comment] 2024-01-17 18:05
@dacoaster it is editable there, just tested on a last `main`
<img width="676" alt="image" src="https://github.com/yatt-ai/yattie/assets/23207978/8c6a7152-71b5-4b00-9934-c03cc896a868">
Probably we can close this issue

**Closed** 2024-02-04 18:44 UTC
Labels: bug
